AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for Nested application resources
Resources:
  Auth:
    Type: AWS::Serverless::Application
    Properties:
      Location: cognito/cognito.yaml
      Parameters:
        ServerlessJavaCallbackUrl: 'http://localhost:4200/callback'

  S3MetadataDynamodb:
    Type: AWS::Serverless::Application
    Properties:
      Location: s3-metadata-sync/s3-metadata-sync-dynamodb.yaml
      Parameters:
        TableName: serverless-java-s3-metadata-table

  S3MetadataSyncTrigger:
    Type: AWS::Serverless::Application
    Properties:
      Location: s3-metadata-sync/s3-metadata-sync-trigger.yaml
      Parameters:
        S3MetadataDynamoDbArn: !GetAtt S3MetadataDynamodb.Outputs.Arn
        S3MetadataDynamoDbName: !GetAtt S3MetadataDynamodb.Outputs.Name
    DependsOn: S3MetadataDynamodb

  S3MetadataApi:
    Type: AWS::Serverless::Application
    Properties:
      Location: s3-metadata-sync/s3-metadata-rest-api.yaml
      Parameters:
        S3MetadataDynamoDbName: !GetAtt S3MetadataDynamodb.Outputs.Name
        UserPoolId: !GetAtt Auth.Outputs.UserPoolId
    DependsOn:
      - S3MetadataDynamodb
      - Auth

  S3UserStorageBucket:
    Type: AWS::Serverless::Application
    Properties:
      Location: s3-user-storage/s3-user-storage.yaml
      Parameters:
        SyncTriggerName: !GetAtt S3MetadataSyncTrigger.Outputs.FunctionName
        SyncTriggerArn: !GetAtt S3MetadataSyncTrigger.Outputs.FunctionArn
        SyncExecutionRole: !GetAtt S3MetadataSyncTrigger.Outputs.ExecutionRoleName
        BucketName: serverless-java-s3-storage
    DependsOn: S3MetadataSyncTrigger
