### GET through REST API
GET {{rest-api-url}}/s3-metadata/files
Authorization: Bearer {{$auth.token("auth-code-flow")}}

### POST through REST API
POST {{rest-api-url}}/s3-metadata/files
Authorization: Bearer {{$auth.token("auth-code-flow")}}
Content-Type: application/json

{
  "s3Key" : "/my-key/my-file.pdf",

  "fileSize" : 200,
  "eTag" :  "etag"
}

### DELETE through REST API
DELETE {{rest-api-url}}/s3-metadata/files?partitionKey=/my-key/my-file.pdf
Authorization: Bearer {{$auth.token("auth-code-flow")}}

// Methods below are not publicly available in AWS. They're triggered by S3.
### Object created though Lambda S3 Trigger Event
POST http://localhost:8081
Content-Type: application/json

{
  "Records":[
    {
      "eventName": "ObjectCreated:Put",
      "s3": {
        "object": {
          "key": "uploads/my-file.txt",
          "size": 12345,
          "eTag": "098f6bcd4621d373cade4e832627b4f6"
        }
      }
    }
  ]
}

### Object deleted though Lambda S3 Trigger Event
POST http://localhost:8081
Content-Type: application/json

{
  "Records":[
    {
      "eventName": "ObjectRemoved:Delete",
      "s3": {
        "object": {
          "key": "uploads/my-file.txt",
          "size": 12345,
          "eTag": "098f6bcd4621d373cade4e832627b4f6"
        }
      }
    }
  ]
}